### ISSUE TITLE
Agent is preferring "sideways" posters for some movies

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/MoviePosterDB.bundle#3]
Based on testing triggered from https://forums.plex.tv/index.php/topic/113777-plex-covers-are-often-sideways/, the agent appears to be preferring "sideways" posters for some movies.

Example:
Movie: Blue Valentine (2010)
MoviePosterDB posters: http://www.movieposterdb.com/movie/1120985/Blue-Valentine.html?cid=1
Chosen poster: http://www.movieposterdb.com/poster/e2ef0ce6 (except it's displayed sideways)

![screenshot 7 7 14 jul 7 6 56 pm](https://cloud.githubusercontent.com/assets/1161845/3503511/6e83eabe-0632-11e4-89ef-df34bb1a6ae0.png)
![screenshot 7 7 14 jul 7 6 57 pm](https://cloud.githubusercontent.com/assets/1161845/3503519/9f0c15ee-0632-11e4-9528-433ce966749e.png)

Other examples:
[Master & Commander](http://www.movieposterdb.com/movie/0311113/Master-and-Commander-The-Far-Side-of-the-World.html) (2003)
[I Am Bruce Lee](http://www.movieposterdb.com/movie/1954299/I-Am-Bruce-Lee.html) (2012)

In all these cases, the poster chosen appears to be the one with the largest dimensions, but it's not the one that seems to be indicated as the main/preferred one on the site.

/cc @mmccurdy07

**Comment by maxGreenblatt** [comment]
Closing since this isn't possible for us to fix.
